sudo: false

language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4

before_install:
  - SRC_DIR=$(pwd)
  - REDIRECT_TO=/dev/null # change to /dev/stdout to unsilence travis

install:
  - pip install -q pytest future pytest-cov pytest-capturelog
  - pip install -q coveralls

script:
  - cd ${SRC_DIR}
  - python setup.py install > ${REDIRECT_TO}
  - py.test tests -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls;
