name: Documentation building
on:
  schedule:
    - cron: '0 0 * * 3'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - pyclibrary/*
      - docs/*
      - setup.py

jobs:
  docs:
    name: Docs building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install project
        run: |
          pip install .
      - name: Install graphviz
        uses: kamiazya/setup-graphviz@v1
      - name: Install doc building tools
        run: |
          pip install --group docs
      - name: Build documentation
        run: |
          mkdir docs_output;
          sphinx-build docs/source docs_output -W -b html;
